[repo]
name = ""
owner = "ijsKoud"
description = "An open-source customisable solution to storing files in the cloud. ✈️"
license = "MIT"

[project]
icon = "apps/web/public/logo/text.png"
icon_width = "500px"
version = "4.3.1"

[variables]
information = [ "- Customisable ✏️", "- Blazingly fast thanks to Next.js ⚡", "- File uploading and URL shortening ☁️", "- Password Protection for files 🔐", "- Discord Embeds using OG Metadata 🔗", "- 2FA Authentication to protect the vulnerable data 🔄️", "- Gallery and Table viewing options 📃", "- Support for multiple users using domains 🧑‍🤝‍🧑", "- Clean and modern design 🖌️", "- User invite-only mode 📨", "- Backup import and export functionality 📂", "- Easy install using Docker! 🚢" ]
installation = [ "The following guide only shows you the Docker installation steps, for more details visit [the documentation page](https://paperplane.ijskoud.dev/). We are using `~/paperplane` as data folder, `paperplane` as name for the docker container and port `3000` (the first one and not the second one) here, you can customise all the options.\n", "```bash\ndocker pull ghcr.io/ijskoud/paperplane:latest\ndocker run --name=paperplane -d -v ~/paperplane:/paperplane/data -p 3000:3000 ghcr.io/ijskoud/paperplane:latest\n```" ]