name: "Ci: Eslint & Build Testing"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

      - name: Install Node v16
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

      - name: Install Node v16
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma Types
        run: yarn prisma:generate

      - name: TypeScript Compiler
        run: yarn build
